# Generated by Django 4.2.6 on 2023-10-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='postCategory',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='category',
            new_name='categoryThrough',
        ),
    ]
